name: Train and Inference

on:
  push:
    branches:
      - main

jobs:
  train_and_inference:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate Dataset
      run: python generate_dataset.py

    - name: Train Model
      run: python train_model.py

    - name: Run Inference
      run: python run_inference.py

