name: SLSA for ML models example
on:
  workflow_dispatch:
    inputs:
      model_type:
        description: Name of the model (implies framework)
        required: true
        type: choice
        options:
        - model.pth
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths-ignore:
      - '**/*.md'
      - '*.md'

permissions: read-all

defaults:
  run:
    shell: bash

jobs:
  train:
    name: Train model
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Don't cancel other jobs if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    outputs:
      hash-ubuntu-latest: ${{ steps.hash.outputs.hash-ubuntu-latest }}
      hash-macos-latest: ${{ steps.hash.outputs.hash-macos-latest }}
      hash-windows-latest: ${{ steps.hash.outputs.hash-windows-latest }}
    steps:
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: 3.18
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build model
      env:
        MODEL_TYPE: ${{ github.event.inputs.model_type || 'model.pth' }}
      run: |
        set -exuo pipefail
        python -m venv venv
        .github/workflows/scripts/venv_activate.sh
        python slsa_for_models/main.py "$MODEL_TYPE"
    - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        path: ${{ github.event.inputs.model_type || 'model.pth' }}
        name: ${{ github.event.inputs.model_type || 'model.pth' }}_${{ runner.os }}
        if-no-files-found: error
    - id: hash
      env:
        MODEL: ${{ github.event.inputs.model_type || 'model.pth' }}
      run: |
        set -euo pipefail
        (sha256sum -t "$MODEL" || shasum -a 256 "$MODEL") > checksum
        echo "hash-${{ matrix.os }}=$(base64 -w0 checksum || base64 checksum)" >> "${GITHUB_OUTPUT}"

  provenance:
    if: ${{ github.event_name != 'pull_request' }}
    needs: [train]
    strategy:
      fail-fast: false # Don't cancel other jobs if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.9.0
    with:
      base64-subjects: "${{ needs.train.outputs[format('hash-{0}', matrix.os)] }}"
      upload-assets: true # NOTE: This does nothing unless 'upload-tag-name' parameter is also set to an existing tag